### ISSUE TITLE
Some Implementation Details & Personal Usage? 

### ISSUE THREAD

**Issue by regymm** [fandahao17/FPGAOL-Examples#1]
Hi, 我是科大学生，FPGA 算是业余爱好，因为感觉随身带着板子才能开发很麻烦，正好手头又有树莓派，想着能不能自己搞一套类似的东西远程调试。

关于实现细节，想问一下烧写 Bitstream 用的是什么方式呢？类似 OpenOCD 播放 JTAG 信号吗？
还有平时调软核（懒得仿真）用 ILA 抓波形，不知道 FPGAOL 能不能远程用 ILA 呢？

Thanks!

**Comment by fandahao17** [comment]
Hi, Peter! 感谢你对FPGAOL的支持！

FPGAOL后端烧写bitstream时，使用的是djtgcfg，它是一个命令行工具，可以烧写bitstream，但是我现在找不到它的下载地址了，你如果需要的话可以找一找。

我不太了解ILA工具，目前FPGAOL后端用的是pigpio来实时记录输入和输出信号的波形，我感觉用ILA或许是个不错的尝试方向，我们会了解一下试试看。

因为FPGAOL是本科生开发和维护的，所以比较缺人手，更新得不是很快，如果你感兴趣也可以和我们一起来搞呀！

**Comment by cyh-ustc** [comment]
fpgaol用的开发板是nexys 4
烧写工具是adept
链接在https://reference.digilentinc.com/lib/exe/fetch.php?tok=f5f244&media=https%3A%2F%2Fmautic.digilentinc.com%2Fadept-runtime-download
ila的话由于要debug线之类，现有的硬件连线是不能支持的

**Comment by regymm** [comment]
感谢回复！感觉 FPGAOL 挺有意思的，有空仔细了解一下。

**Comment by fandahao17** [comment]
本仓库现已迁移至[这里](https://git.ustc.edu.cn/hexuustc/fpgaol-examples)。

**Comment by whentojump** [comment]
您好，这里是友校学生，感觉这个项目很有意思！冒昧问一下服务端软/硬件有计划开源吗？

感觉稍微改一下就能衍生出很多好玩的东西:smile:，例如把FPGA换成MCU或PLC，适用于树莓派的烧写工具基本都有现成的：[`stm32flash`](https://sourceforge.net/projects/stm32flash/)、[`st-link`](https://github.com/stlink-org/stlink)、[`idf`](https://github.com/espressif/esp-idf)……

**Comment by fandahao17** [comment]
@whentojump 谢谢你对FPGAOL的关注！

我目前已经毕业，不再负责这个项目了，项目的最新进展可以在[这个仓库](https://git.ustc.edu.cn/hexuustc/fpgaol-examples)看到。我问了一下，目前团队在讨论开源的事情，如果有进展会及时发布😃
